name: Show GitHub Context
on:
    schedule:
        - cron: '*/10 * * * *'
    workflow_dispatch:
jobs:
    print-actor:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ github.actor }}"
    print-branch:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ github.head_ref }}"