name: Show GitHub Context
on:
    schedule:
        - cron: '*/10 * * * *'
    workflow_dispatch:
jobs:
    print-actor:
        runs-on: ubuntu-latest
        env:
            ACTOR: ${{ github.actor }}
        steps:
            - run: echo "${ACTOR}"
    print-branch:
        runs-on: ubuntu-latest
        env:
            BRANCH: ${{ github.head_ref }}
        steps:
            - run: echo "${BRANCH}"