name: Status check functions
on:
    push:
    workflow_dispatch:
jobs:
    fail:
        runs-on: ubuntu-latest
        steps:
            - run: exit 1
            - run: echo "when failure"
              if: ${{ failure() }}
            - run: echo "always"
              if: ${{ always() }}